<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxvdz0a\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxvdz0a/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDxvdz0a.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDxvdz0a\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDxvdz0a\appProdProjectContainer([
    'container.build_hash' => 'Dxvdz0a',
    'container.build_id' => 'a101a422',
    'container.build_time' => 1592728774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxvdz0a');
